laberinto/laberinto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("leyenda/",
         include("leyenda.urls", namespace="leyenda"),
         name="leyenda")
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

laberinto/leyenda/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (IndiceLeyendasView,
                    # IcaroView,
                    # MinotauroView,
                    LeyendaView)

app_name = "leyenda"

# /leyenda/indice -> IndiceLeyendasView
urlpatterns = [
    path("indice",
         IndiceLeyendasView.as_view(),
         name="indice"),
    # path("icaro",
    #      IcaroView.as_view(),
    #      name="icaro"),
    # path("minotauro",
    #      MinotauroView.as_view(),
    #      name="minotauro"),
    path("nombre=<slug>/",
         LeyendaView.as_view(),
         name="nombre")
]

laberinto/leyenda/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField

from django.urls import reverse

# Create your models here.

class Leyenda(models.Model):
    titulo=models.CharField(
        max_length=124)
    fecha = models.DateTimeField(
        auto_now=True)
    slug=AutoSlugField(populate_from="titulo")
    resumen = models.TextField()
    texto = models.TextField()
    imagen = models.ImageField(upload_to="imagenes")

    def get_absolute_url(self):
        return reverse("leyenda:nombre",
                       kwargs={"nombre":self.slug})

    def __str__(self):
        return f"Leyenda({self.titulo})"

    def __repr__(self):
        return f"Leyenda({self.titulo}, {self.fecha})"

    class Meta:
        app_label = "leyenda"
        verbose_name = "Leyenda"
        verbose_name_plural = "Leyendas"
        ordering = ("-fecha", "titulo")

laberinto/leyenda/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView

from .textos import diccionario
from .models import Leyenda
from pprint import pprint

# Create your views here.
class IndiceLeyendasView(ListView):
    model = Leyenda
    template_name = "leyenda/index.dj.html"
    context_object_name = "leyendas"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(
    #         **kwargs)
    #     print(context)
    #     #context.update({"leyendas":diccionario})
    #     return context

class IcaroView(TemplateView):
    template_name = 'leyenda/icaro.dj.html'


class MinotauroView(TemplateView):
    template_name = 'leyenda/minotauro.dj.html'


class LeyendaView(DetailView):
    model = Leyenda
    template_name = 'leyenda/texto.dj.html'
    context_object_name = "leyenda"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     nombre = context.get('nombre')
    #     leyenda = diccionario.get(nombre,{})
    #     if not leyenda:
    #         leyenda = {"texto":f"No existe leyenda {nombre}"}
    #     pprint(leyenda)
    #     context.update(leyenda)
    #     return context

laberinto/leyenda/templates/leyenda/base_app.dj.html
{% extends "base.dj.html" %}
{% load static %}


{% block extra_css %}
<link
    rel="stylesheet"
    href="{% static 'leyenda/css/estilos.css' %}">
{% endblock %}

laberinto/leyenda/templates/leyenda/icaro.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>Leyenda de Ícaro</h1>
{% endblock encabezado %}


{% block contenido %}

<section>
    <a href="{% url 'leyenda:indice' %}">Índice</a>
</section>

<p>En la <a href="/wiki/Mitolog%C3%ADa_griega" title="Mitología griega">mitología griega</a>, <b>Ícaro</b> (en <a href="/wiki/Griego_antiguo" title="">griego antiguo</a> Ἴκαρος <i>Ikaros</i>) es hijo del arquitecto <a href="/wiki/D%C3%A9dalo" title="Dédalo">Dédalo</a>, constructor del <a href="/wiki/Laberinto_de_Creta" title="Laberinto de Creta">laberinto de Creta</a>, y de una esclava llamada <a href="/wiki/N%C3%A1ucrate" title="Náucrate">Náucrate</a>.<sup id="cite_ref-1" class="reference separada"><a href="#cite_note-1"><span class="corchete-llamada">[</span>1<span class="corchete-llamada">]</span></a></sup>​ 
</p><p>Ícaro estaba retenido junto a su padre, Dédalo, en la isla de <a href="/wiki/Creta" title="Creta">Creta</a> por el rey de la isla, llamado <a href="/wiki/Minos" title="Minos">Minos</a>.
</p><p>Dédalo decidió escapar de la isla en secreto, pero dado que Minos controlaba las aguas y la tierra , Dédalo se puso a trabajar para fabricar alas para él y su joven hijo, Ícaro. Enlazó plumas entre sí uniendo con hilo las plumas centrales y con cera las laterales, y le dio al conjunto la suave curvatura de las alas de un pájaro. Ícaro a veces corría a recoger del suelo las plumas que el viento se había llevado o ablandaba la cera.
</p><p>Cuando al fin terminó el trabajo, Dédalo batió sus alas y se halló subiendo y suspendido en el aire. Equipó entonces a su hijo de la misma manera, y le enseñó cómo volar. Cuando ambos estuvieron preparados para volar, Dédalo advirtió a Ícaro que no volase demasiado alto porque el calor del sol derretiría la cera, ni demasiado bajo porque la espuma del mar mojaría las alas y no podría volar. 
</p><p>Pasaron las islas de <a href="/wiki/Samos" title="Samos">Samos</a>, <a href="/wiki/Delos" title="Delos">Delos</a>, <a href="/wiki/Paros" title="Paros">Paros</a>, <a href="/wiki/Lebintos" class="mw-redirect" title="Lebintos">Lebintos</a> y <a href="/wiki/Calimna" class="mw-redirect" title="Calimna">Calimna</a>, entonces el muchacho comenzó a ascender. El ardiente sol ablandó la cera que mantenía unidas las plumas y estas se despegaron. Ícaro agitó sus brazos, pero no quedaban suficientes plumas para sostenerlo en el aire y cayó al mar. Su padre lloró y lamentando amargamente sus artes, y, en su memoria, llamó <a href="/wiki/Icaria" title="Icaria">Icaria</a> a la tierra cercana al lugar del mar en el que Ícaro había caído.<sup id="cite_ref-2" class="reference separada"><a href="#cite_note-2"><span class="corchete-llamada">[</span>2<span class="corchete-llamada">]</span></a></sup>​
</p><p>Dédalo llegó sano y salvo a <a href="/wiki/Sicilia" title="Sicilia">Sicilia</a>, donde quedó bajo la protección del rey <a href="/wiki/C%C3%B3calo" title="Cócalo">Cócalo</a>.<sup id="cite_ref-3" class="reference separada"><a href="#cite_note-3"><span class="corchete-llamada">[</span>3<span class="corchete-llamada">]</span></a></sup>​ Allí construyó un templo a <a href="/wiki/Apolo" title="Apolo">Apolo</a> en el que colgó sus alas como ofrenda al dios.
</p><p><a href="/wiki/Pausanias_(ge%C3%B3grafo)" title="Pausanias (geógrafo)">Pausanias</a> cuenta una versión más prosaica en la que ambos huían de <a href="/wiki/Creta" title="Creta">Creta</a> en pequeñas barcas, para lo cual Dédalo inventa el principio de la <a href="/wiki/Vela_(n%C3%A1utica)" title="Vela (náutica)">vela</a>, desconocido hasta entonces para los hombres. Ícaro, navegante torpe, naufragó frente a la costa de Samos, en cuyas orillas se encontró su cuerpo. <a href="/wiki/Heracles" title="Heracles">Heracles</a> le dio sepultura en esa tierra, que desde entonces se llama Icaria, y el mar que está junto a ella recibió el nombre de <a href="/w/index.php?title=Mar_Icario&amp;action=edit&amp;redlink=1" class="new" title="Mar Icario (aún no redactado)">mar Icario</a>.<sup id="cite_ref-4" class="reference separada"><a href="#cite_note-4"><span class="corchete-llamada">[</span>4<span class="corchete-llamada">]</span></a></sup>​
</p>
{% endblock contenido %}

laberinto/leyenda/templates/leyenda/index.dj.html
{% extends "leyenda/base_app.dj.html" %}

{% block encabezado %}
<h1>Índice de leyendas sobre laberintos</h1>
{% endblock encabezado %}


{% block contenido %}
<ul id="indice-leyendas">
    {% for leyenda in leyendas %}
    <li>
        {% include 'leyenda/item_link.dj.html' %}
    </li>
    {% endfor %}
</ul>
{% endblock contenido %}

laberinto/leyenda/templates/leyenda/item_link.dj.html
{% load static %}

<div id="item-link" class="pure-g">
    <!-- imagen del contenido -->
    <div
        id="imagen-item-link"
        class="pure-u-8-24"
    >
        <figure>
            <a
                href="{% url 'leyenda:nombre' leyenda.slug %}"
            >
            <img
                class="pure-img"
                src="{{MEDIA_URL}}{{leyenda.imagen}}"
            >
            </a>
        </figure>
    </div>
    <!-- contenido texto -->
    <div
        id="contenido-item-link"
        class="pure-u-16-24"
    >
        <h4>{{leyenda.titulo}}</h4>
        <section>
            <p>{{leyenda.resumen}}</p>
        </section>
        <a
            href="{% url 'leyenda:nombre' leyenda.slug %}"
        >
            ver
        </a>
    </div>
</div>

laberinto/leyenda/templates/leyenda/minotauro.dj.html
{% extends "base.dj.html" %}

{% block encabezado %}
<h1>Leyenda de Ícaro</h1>
{% endblock encabezado %}


{% block contenido %}

<section>
    <a href="{% url 'leyenda:indice' %}">Índice</a>
</section>


<p>El <b>Minotauro</b> (del griego Μινώταυρος [<i>Minótauros</i>]) es un <a href="/wiki/Monstruo" title="Monstruo">monstruo</a> mitológico de la <a href="/wiki/Mitolog%C3%ADa_griega" title="">mitología griega</a>, con cuerpo de hombre y cabeza de <a href="/wiki/Bos_primigenius_taurus" title="Bos primigenius taurus">toro</a>. Su nombre significa "Toro de <a href="/wiki/Minos" title="Minos">Minos</a>", y era hijo de <a href="/wiki/Pas%C3%ADfae" title="Pasífae">Pasífae</a> y el <a href="/wiki/Toro_de_Creta" title="Toro de Creta">Toro de Creta</a>. Fue encerrado en un <a href="/wiki/Laberinto_de_Creta" title="Laberinto de Creta">laberinto</a> diseñado por el artesano <a href="/wiki/D%C3%A9dalo" title="Dédalo">Dédalo</a>, hecho expresamente para retenerlo,<sup id="cite_ref-1" class="reference separada"><a href="#cite_note-1"><span class="corchete-llamada">[</span>1<span class="corchete-llamada">]</span></a></sup>​ ubicado en la ciudad de <a href="/wiki/Cnosos" title="Cnosos">Cnosos</a> en la isla de <a href="/wiki/Creta" title="Creta">Creta</a>. Durante muchos años, siete hombres y otras siete mujeres eran llevados al laberinto como sacrificio para ser el alimento de la bestia hasta que la vida de este terminó en manos del héroe <a href="/wiki/Teseo" title="Teseo">Teseo</a>. Los catorce jóvenes eran internados en el laberinto, donde vagaban perdidos hasta ser encontrados por el Minotauro. El <a href="/wiki/Mito" title="Mito">mito</a> tiene su versión más completa en la <i><a href="/wiki/Biblioteca_mitol%C3%B3gica" title="Biblioteca mitológica">Biblioteca mitológica</a></i> de <a href="/wiki/Apolodoro_de_Atenas" title="Apolodoro de Atenas">Apolodoro</a>.

{% endblock contenido %}

laberinto/leyenda/templates/leyenda/texto.dj.html
{% extends "leyenda/base_app.dj.html" %}

{% block encabezado %}
<h1>{{leyenda.titulo}}</h1>
{% endblock encabezado %}


{% block contenido %}
<figure id="imagen-item">
    <img
        src="{{MEDIA_URL}}{{leyenda.imagen}}"
    >
</figure>
<section>
    <a href="{% url 'leyenda:indice' %}">Índice</a>
</section>
{{leyenda.texto|safe}}
{% endblock contenido %}

laberinto/templates/base.dj.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{titulo}}</title>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1">
        {% include "estilos.dj.html" %}
        {% block extra_css %}
        {% endblock %}
    </head>
    <body id="cuerpo">
        <div
            id="encabezado"
            class="">
        {% block encabezado %}
        {% endblock encabezado %}
        </div>
        <article
            id="contenido">
            <div class="">
            {% block menu %}
            {% endblock menu %}
            </div>
            <div class="">
            {% block contenido %}
            {% endblock contenido %}
            </div>
        </article>
    </body>
</html>

laberinto/templates/estilos.dj.html
<link
    rel="stylesheet"
    href="https://unpkg.com/purecss@2.0.6/build/pure-min.css"
    integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5"
    crossorigin="anonymous">
<link
    rel="stylesheet"
    href="https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css">